-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)


type AggregateUser
    = AggregateUser


type BatchPayload
    = BatchPayload


type PageInfo
    = PageInfo


type User
    = User


type UserConnection
    = UserConnection


type UserEdge
    = UserEdge


type UserPreviousValues
    = UserPreviousValues


type UserSubscriptionPayload
    = UserSubscriptionPayload
