-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object exposing (..)


type AggregateInterest
    = AggregateInterest


type AggregateUser
    = AggregateUser


type BatchPayload
    = BatchPayload


type Interest
    = Interest


type InterestConnection
    = InterestConnection


type InterestEdge
    = InterestEdge


type InterestPreviousValues
    = InterestPreviousValues


type InterestSubscriptionPayload
    = InterestSubscriptionPayload


type PageInfo
    = PageInfo


type User
    = User


type UserConnection
    = UserConnection


type UserEdge
    = UserEdge


type UserPreviousValues
    = UserPreviousValues


type UserSubscriptionPayload
    = UserSubscriptionPayload
