-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Subscription exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Graphql.Internal.Builder.Object as Object
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Json.Decode as Decode exposing (Decoder)
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a top-level mutation. The request can be sent with
functions from `Graphql.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootSubscription
selection constructor =
    Object.selection constructor
type alias UserOptionalArguments = { where_ : OptionalArgument Api.InputObject.UserSubscriptionWhereInput }

{-|

  - where_ - 

-}
user : (UserOptionalArguments -> UserOptionalArguments) -> SelectionSet decodesTo Api.Object.UserSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
user fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ (Api.InputObject.encodeUserSubscriptionWhereInput) ]
                |> List.filterMap identity
    in
      Object.selectionField "user" optionalArgs (object_) (identity >> Decode.nullable)


type alias InterestOptionalArguments = { where_ : OptionalArgument Api.InputObject.InterestSubscriptionWhereInput }

{-|

  - where_ - 

-}
interest : (InterestOptionalArguments -> InterestOptionalArguments) -> SelectionSet decodesTo Api.Object.InterestSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
interest fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ (Api.InputObject.encodeInterestSubscriptionWhereInput) ]
                |> List.filterMap identity
    in
      Object.selectionField "interest" optionalArgs (object_) (identity >> Decode.nullable)


type alias TimeSlotOptionalArguments = { where_ : OptionalArgument Api.InputObject.TimeSlotSubscriptionWhereInput }

{-|

  - where_ - 

-}
timeSlot : (TimeSlotOptionalArguments -> TimeSlotOptionalArguments) -> SelectionSet decodesTo Api.Object.TimeSlotSubscriptionPayload -> Field (Maybe decodesTo) RootSubscription
timeSlot fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ (Api.InputObject.encodeTimeSlotSubscriptionWhereInput) ]
                |> List.filterMap identity
    in
      Object.selectionField "timeSlot" optionalArgs (object_) (identity >> Decode.nullable)
