-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Enum.PrismaDatabase exposing (..)

import Json.Decode as Decode exposing (Decoder)


type PrismaDatabase
    = Default
list : List PrismaDatabase
list =
    [Default]
decoder : Decoder PrismaDatabase
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "default" ->
                        Decode.succeed Default

                    _ ->
                        Decode.fail ("Invalid PrismaDatabase type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
        )
        

{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PrismaDatabase -> String
toString enum =
    case enum of
        Default ->
                "default"
