-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.InterestConnection exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.InterestConnection
selection constructor =
    Object.selection constructor
{-| Information to aid in pagination.
-}
pageInfo : SelectionSet decodesTo Api.Object.PageInfo -> Field decodesTo Api.Object.InterestConnection
pageInfo object_ =
      Object.selectionField "pageInfo" [] (object_) (identity)


{-| A list of edges.
-}
edges : SelectionSet decodesTo Api.Object.InterestEdge -> Field (List (Maybe decodesTo)) Api.Object.InterestConnection
edges object_ =
      Object.selectionField "edges" [] (object_) (identity >> Decode.nullable >> Decode.list)


aggregate : SelectionSet decodesTo Api.Object.AggregateInterest -> Field decodesTo Api.Object.InterestConnection
aggregate object_ =
      Object.selectionField "aggregate" [] (object_) (identity)
