-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.PageInfo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.PageInfo
selection constructor =
    Object.selection constructor
{-| When paginating forwards, are there more items?
-}
hasNextPage : Field Bool Api.Object.PageInfo
hasNextPage =
      Object.fieldDecoder "hasNextPage" [] (Decode.bool)


{-| When paginating backwards, are there more items?
-}
hasPreviousPage : Field Bool Api.Object.PageInfo
hasPreviousPage =
      Object.fieldDecoder "hasPreviousPage" [] (Decode.bool)


{-| When paginating backwards, the cursor to continue.
-}
startCursor : Field (Maybe String) Api.Object.PageInfo
startCursor =
      Object.fieldDecoder "startCursor" [] (Decode.string |> Decode.nullable)


{-| When paginating forwards, the cursor to continue.
-}
endCursor : Field (Maybe String) Api.Object.PageInfo
endCursor =
      Object.fieldDecoder "endCursor" [] (Decode.string |> Decode.nullable)
